// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/api/_lib/db.ts";
import * as $2 from "./routes/api/_lib/mod.ts";
import * as $3 from "./routes/api/create.ts";
import * as $4 from "./routes/api/join.ts";
import * as $5 from "./routes/api/reset.ts";
import * as $6 from "./routes/bestact.ts";
import * as $7 from "./routes/index.ts";
import * as $8 from "./routes/saved/[name]/[cards].ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/api/_lib/db.ts": $1,
    "./routes/api/_lib/mod.ts": $2,
    "./routes/api/create.ts": $3,
    "./routes/api/join.ts": $4,
    "./routes/api/reset.ts": $5,
    "./routes/bestact.ts": $6,
    "./routes/index.ts": $7,
    "./routes/saved/[name]/[cards].ts": $8,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
